### ISSUE TITLE
Java Heap Space

### ISSUE THREAD

**Issue by XeonFaux** [bdew-hnh/combiner#1]
So the combiner ran out of memory or something while trying to combine a very large map, any way around this, or a fix that could be implemented? I'd very much like to have my map, lol. Here's the full error dialog screen shot.

http://puu.sh/kG2oy/5f3db615f4.png

**Comment by XeonFaux** [comment]
Nevermind, found out from one of the latest forum posts, that adding "-Xmx1G" for example, was able to manipulate the amount of memory I put into the combiner. Turns out I needed 4 gigabytes, heh....

**Comment by bdew** [comment]
Yeah for now -Xmx1G (you can also do more with 2G, 10G, etc.) is the fix.

You need ~40kb for every 100x100 tile, including those that are empty in the resulting map. So for example a 150x150 map will need 900MB of memory + overhead.

In the future i would like to do a streaming PNG generator that can render maps without holding the whole thing in RAM.
